server:
  port: 8761

spring:
  application:
    name: discoveryservice
eureka:
  client:
    # ??? ?? ??? ??? ??? ???? false ??
    register-with-eureka: false # default : true
    fetch-registry: false # default : true
